name: Redlin Painting
favicon: null
layout_spectrum: 0.05765232024714351
typography_spectrum: 0.4535622503608465
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#991b1e'
    - '#040707'
    - '#dfd2cb'
    - '#b7ac98'
    - '#4b4847'
  brandStrength: 0.75
  lightness: 0.32743871095590293
  saturation: 0.8683918714523315
  rhythmicContrast: 0.9397526604589075
purpose: []
